# Users schema

# --- !Ups

CREATE TABLE EVENTS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CURRENT BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CANDIDATES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EVENTID INTEGER NOT NULL,
    NAME VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE VOTES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    VOTER VARCHAR NOT NULL,
    EVENTID INTEGER NOT NULL,
    CANDIDATEID INTEGER NOT NULL,
    CANDIDATENAME VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE VOTES;
DROP TABLE CANDIDATES;
DROP TABLE EVENTS;