# Users schema

# --- !Ups

CREATE TABLE EVENTS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CURRENT BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CANDIDATES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EVENTID INTEGER NOT NULL,
    NAME VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT EVENT_FK FOREIGN KEY (EVENTID) REFERENCES EVENTS(ID) ON UPDATE CASCADE
);

CREATE TABLE VOTES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    VOTER VARCHAR NOT NULL,
    EVENTID INTEGER NOT NULL,
    CANDIDATEID INTEGER NOT NULL,
    CANDIDATENAME VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT EVENT_2_FK FOREIGN KEY (EVENTID) REFERENCES EVENTS(ID) ON UPDATE CASCADE,
    CONSTRAINT CAND_FK FOREIGN KEY (CANDIDATEID) REFERENCES CANDIDATES(ID) ON UPDATE CASCADE
);

CREATE TABLE CACHE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EVENTID INTEGER NOT NULL,
    CANDIDATEID INTEGER NOT NULL,
    CANDIDATENAME VARCHAR NOT NULL,
    VOTES INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT EVENT_3_FK FOREIGN KEY (EVENTID) REFERENCES EVENTS(ID) ON UPDATE CASCADE,
    CONSTRAINT CAND_2_FK FOREIGN KEY (CANDIDATEID) REFERENCES CANDIDATES(ID) ON UPDATE CASCADE
);

# --- !Downs

DROP TABLE VOTES;
DROP TABLE CANDIDATES;
DROP TABLE EVENTS;
DROP TABLE CACHE;